#! /bin/bash

arg1=$1;

function main() {
    if [ -z "$1" ]
        then
        echo "Usage: generateAst <output directory>"
        return 1
    fi

    allTypes=(
        "Binary   : Expr left, Token operator, Expr right"
        "Grouping : Expr expression"
        "Literal  : Object value"
        "Unary    : Token operator, Expr right"
    )

    defineAst $1 "Expr" "${allTypes[@]}"
}

function defineAst() {
    local outputDir=$1
    local baseName=$2
    local path="$outputDir/$baseName.java"

    shift
    local types=("$@")
    local fileName=$baseName.java

    echo "the path is: $path"

    echo "package com.craftinginterpreters.lox;" > $fileName
    echo "" >> $fileName
    echo "import java.util.List;" >> $fileName
    echo "" >> $fileName
    echo "abstract class $baseName {" >> $fileName

    defineVisitor $fileName $baseName "${types[@]}"

    # The AST classes.
    for type in "${types[@]}"; do
        className=$(echo "$type" | cut -d':' -f1 | tr -d '[:space:]')
        fields=$(echo "$type" | cut -d':' -f2 | tr -d '[:space:]')
        # echo "Class Name: $className"
        # echo "Fields: $fields"
    done

    # The base accept() method.
    # echo "" >> $fileName
    # echo "  abstract <R> R accept(Visitor<R> visitor);" >> $fileName
    # echo "}" >> $fileName
}

function defineVisitor() {
    local fileName=$1
    local baseName=$2

    shift
    shift
    shift

    local types=("$@")

    echo "  interface Visitor<R> {" >> $fileName

    for type in "${types[@]}"; do
        typeName=$(echo "$type" | cut -d':' -f1 | tr -d '[:space:]')
        baseNameLower=$(echo "$baseName" | tr '[:upper:]' '[:lower:]')
    
        echo "    R visit${typeName}${baseName}(${typeName} ${baseNameLower});" >> $fileName 
    done
    
    echo "  }" >> $fileName
}

main $arg1 