#! /bin/bash

lang=$1

case $lang in

  bash)
    ./com/craftinginterpreters/tool/generateAst com/craftinginterpreters/lox
    ;;

  java)
    javac com/craftinginterpreters/tool/GenerateAst.java
    java com/craftinginterpreters/tool/GenerateAst com/craftinginterpreters/lox
    ;;

  js)
    node ./com/craftinginterpreters/tool/generateAst.js com/craftinginterpreters/lox
    ;;

  py)
    python3 ./com/craftinginterpreters/tool/generateAst.py com/craftinginterpreters/lox
    ;;

  go)
    go run ./com/craftinginterpreters/tool/generateAst.go com/craftinginterpreters/lox
    ;;

  *)
    echo "invalid input"
    ;;
esac

