#! /bin/bash

lang=$1

case $lang in

  bash)
    ./com/craftinginterpreters/tool/generateAst com/craftinginterpreters/lox
    ;;

  js)
    node ./com/craftinginterpreters/tool/generateAst.js com/craftinginterpreters/lox
    ;;

  java)
    javac com/craftinginterpreters/tool/GenerateAst.java
    java com/craftinginterpreters/tool/GenerateAst com/craftinginterpreters/lox
    ;;

  *)
    echo "invalid input"
    ;;
esac

